### ISSUE TITLE
GH Actions, tftest.TerraformTestError: Error decoding plan output: Expecting value: line 1 column 2 (char 1)

### ISSUE THREAD

**Issue by djsd123** [GoogleCloudPlatform/terraform-python-testing-helper#54]
Hi, I've been unsuccessful in debugging this error.  It appears to emanate from the JSON decoder. However, this only occurs when tests are on a GitHub action. Works without error locally.

**Stack**
```
  if not output:
        return self.execute_command('plan', *cmd_args).out
      with tempfile.NamedTemporaryFile() as fp:
        fp.close()
      # for tg we need to specify a temp name that is relative for the output to go into each
      # of the .terragrunt-cache, then plan / show would work, otherwise it overwrites each other!
      temp_file = fp.name if len(
          self._tg_ra()) == 0 else os.path.basename(fp.name)
      cmd_args.append('-out={}'.format(temp_file))
      self.execute_command('plan', *cmd_args)
      result = self.execute_command('show', '-no-color', '-json', temp_file)
      try:
        return self._plan_formatter(result.out)
      except json.JSONDecodeError as e:
>       raise TerraformTestError(
            'Error decoding plan output: {}'.format(e))
E       tftest.TerraformTestError: Error decoding plan output: Expecting value: line 1 column 2 (char 1)
```

**Code**
```
@pytest.fixture(scope='session')
def fixtures_dir():
    return os.path.join(os.path.dirname(os.path.abspath(__file__)), 'fixtures')

@pytest.fixture(scope='session')
def terraform_binary():
    return shutil.which('terraform')

@pytest.fixture
def plan(fixtures_dir, terraform_binary):
    tf = tftest.TerraformTest(tfdir=fixtures_dir, binary=terraform_binary, env=envs)
    tf.init()
    return tf.plan(output=True)
```

**GH Action**
```
  terraform-test:
    name: Terraform Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test with pytest
        run: python -m pytest test-module-fsx-lustre-monitoring.py
```

**Comment by ludoo** [comment]
Thanks Mikael, I'll try to reproduce and share here whatever I find.

**Comment by djsd123** [comment]
Much appreciated @ludoo 🙏 

To be fair I suspect this may be an issue with the GitHub platform.  I was able to get it working with no apparent tweaks on a vanilla Ubuntu VM. I'm just trying to understand what needs to be done on GitHub actions to get it working.  I've been using tftest on GitHub actions for over a year with no apparent issues.

You are welcome to try with the [terraform-module-fsx-lustre](https://github.com/djsd123/terraform-module-fsx-lustre) repo.

Please let me know if you need anything.

**Comment by ludoo** [comment]
Mikael, can you capture the plan and share it? This issue is weird, as we run hundreds of plans in the Fabric repo via GH workflows, and I also run a few in this repo's tests via GH workflows. I'm curious to see what's in the actual plan, both when executed in a workflow, and in a local machine.

**Comment by ludoo** [comment]
BTW I also tried [bumping up the Terraform version in this repo's workflow](https://github.com/GoogleCloudPlatform/terraform-python-testing-helper/pull/55), but it made no difference.

**Comment by djsd123** [comment]
Morning @ludoo,

Sure thing. At the same time, I'll try tweaking the python setup, to see if there is any change.

[json-plan](https://drive.google.com/file/d/1MqnLjDr7zvAgs6HxE9Ew5VFD4KfM4Eqw/view?usp=sharing)
[binary-plan](https://drive.google.com/file/d/12REKwiIy6Qj92qCsHgAws3CXOTW5uiK-/view?usp=sharing)

**Comment by ludoo** [comment]
Uhm, the plan looks fine of course, which makes me suspect there might be something going on with the temporary file. I am not able to reproduce this (did not try cloning your repo, it's my next move), but would you be able to use a local copy of tftest, and spitting out file name, contents, stats etc inside the `except` clause, just before the exception is raised?

**Comment by ludoo** [comment]
Mikael, have a look at this

https://github.com/ludoo/terraform-module-fsx-lustre/runs/8305377918?check_suite_focus=true

**Comment by ludoo** [comment]
https://stackoverflow.com/questions/73009222/github-actions-terraform-extra-lines-when-piping-to-file

**Comment by ludoo** [comment]
The fix is

```yaml
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2
          terraform_wrapper: false
```
